### PR TITLE
started ui for avatar selection

### PR DESCRIPTION
**Pull request by sfishe10**

### CODE REVIEW

**Comment by sfishe10** [comment]
Submitting pull request for an updated version

**Review by noahgiboney — COMMENTED** [review]
Nice implementation by fetching the avatar path! Something I was wondering if there is a default profile picture when they sign up for the app or are they randomly assigned a avatar. @sfishe10

**Comment by sfishe10** [comment]
Thanks! Right now I have it so that if they don't have an avatar selected, it just shows that chakra Avatar

**Comment by kendricktran** [comment]
Nice job! I like your choice of avatar emojis, we should have a serious team meeting about other possible emojis.

**Comment by Martin-Wise** [comment]
Sweet! Thank you for doing this! I liked how you went with the idea of just having a set number of profile pics, this keeps us from needing to store the images and using a lot of database space. I do agree with Kenrick too, we should group up and see what kind of avatars we want to add

**Comment by MelikaDab** [comment]
This looks great Sadie! I also really like your choice of emojis :) Maybe we can also explore other styles of icons (non emojis) in a team meeting.

**Pull request merged**
