### PR TITLE
Added Name on the sign up

### LINKED ISSUE #59: Add Name to Sign In Flow (1hr)
Added name text field to sign in page and add name to User init in the registration route

### PR DESCRIPTION
**Pull request by noahgiboney**
Added text field for the name and added name to the user init.

Closes #59

### CODE REVIEW

**Comment by sfishe10** [comment]
Looks good!

**Comment by kendricktran** [comment]
LGTM

**Comment by Martin-Wise** [comment]
LGTM2!

**Comment by MelikaDab** [comment]
Awesome!

**Pull request merged**
