### PR TITLE
Homepage (Pt 2)

### PR DESCRIPTION
**Pull request by Martin-Wise**
(Official Homepage PR)
- Linked Homepage with database
- Added Set creation functionality
- Will create a workout if one wasn't created for the day
- (specifically this PR fixes a bug with Set creation but we had to rush the previous PR for the homepage so this is the _official_ one)

### CODE REVIEW

**Comment by noahgiboney** [comment]
Nice work. Only thing I would suggest is to move the several components in homepage to separate files for more readability.

**Comment by Martin-Wise** [comment]
@noahgiboney Yes I plan on doing that in a future iteration, that's definitely a must ahaha

**Comment by kendricktran** [comment]
Awesome! The homepage looks really good

**Comment by sfishe10** [comment]
Nice job, the fixes you implemented look great! I did notice there is still the bug where after you add one exercise, if you try to add another one, the dropdown shows the name of the exercise you just added, instead of "select exercise". I wonder if that would be an easy fix like resetting the inputValue when "confirm" is clicked.

**Comment by Martin-Wise** [comment]
> Nice job, the fixes you implemented look great! I did notice there is still the bug where after you add one exercise, if you try to add another one, the dropdown shows the name of the exercise you just added, instead of "select exercise". I wonder if that would be an easy fix like resetting the inputValue when "confirm" is clicked.

Ohh yes I think it would be something easy like that, I'll look into it! Thank you!

**Comment by MelikaDab** [comment]
This is looking great!

**Pull request merged**
